### ISSUE TITLE
Renaming Organization Url

### ISSUE THREAD

**Issue by ayan-biswas0412** [Google-Summer-of-Code-Archive/gsoc-proposals-archive#9]
Can we give a url like this `GSoC-Archive` , the entire `Google-Summer-of-Code-Archive` looks too big

**Comment by gourab337** [comment]
With so many Summer of Codes coming, it's better to keep the full name in my opinion.

**Comment by RohitDamerr** [comment]
> Can we give a url like this `GSoC-Archive` , the entire `Google-Summer-of-Code-Archive` looks too big

'Gsoc-Archive'
